name: blockchain-explorer
recipe: lamp
config:
  webroot: public
  php: '7.2'
  database: mariadb:10.2
services:
  database:
    type: mariadb:10.2
    portforward: 3306
    creds:
      user: homestead
      password: secret
      database: explorer
